import { supabaseAdmin } from '@/lib/supabase/admin';
import type {
  DeferredCustomerSummary,
  PeriodReport,
  ProductReportRow,
  ReportBusinessDayRow,
  ReportPeriodKey,
  ReportsWorkspace,
  ReportShiftRow,
  ReportTotals,
  StaffPerformanceRow,
  StationCode,
} from '@/lib/ops/types';
import { buildDeferredCustomersWorkspace } from '@/app/api/ops/_server';

type ShiftRow = { id: string; shift_kind: string; status: string; opened_at: string; closed_at: string | null; business_date: string | null };
type BusinessDateRow = { business_date: string | null };
type NamedActorRow = { id: string; full_name: string | null };
type RawMenuProductRef = { id: string; product_name: string | null };
type ItemRow = { shift_id: string; station_code: string | null; unit_price: number | string | null; qty_submitted: number | string | null; qty_ready: number | string | null; qty_delivered: number | string | null; qty_replacement_delivered: number | string | null; qty_paid: number | string | null; qty_deferred: number | string | null; qty_remade: number | string | null; qty_cancelled: number | string | null; qty_waived: number | string | null; menu_products: RawMenuProductRef | RawMenuProductRef[] | null };
type PaymentRow = { shift_id: string; payment_kind: string | null; total_amount: number | string | null; by_staff_id: string | null; by_owner_id: string | null };
type SessionRow = { shift_id: string; status: string | null };
type ComplaintAggRow = { shift_id: string; status: string | null; resolution_kind: string | null; created_by_staff_id: string | null; created_by_owner_id: string | null };
type FulfillmentAggRow = { shift_id: string; event_code: string | null; quantity: number | string | null; by_staff_id: string | null; by_owner_id: string | null };
type ActorMaps = { staffNames: Map<string, string>; ownerNames: Map<string, string> };

function adminOps() { return supabaseAdmin().schema('ops'); }
function cairoToday(): string { return new Intl.DateTimeFormat('en-CA', { timeZone: 'Africa/Cairo', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date()); }
function toDateValue(date: string): Date { return new Date(`${date}T12:00:00Z`); }
function formatDateValue(value: Date): string { return value.toISOString().slice(0, 10); }
function startOfWeek(date: string): string { const value = toDateValue(date); const day = value.getUTCDay(); value.setUTCDate(value.getUTCDate() + (day === 0 ? -6 : 1 - day)); return formatDateValue(value); }
function startOfMonth(date: string): string { const value = toDateValue(date); value.setUTCDate(1); return formatDateValue(value); }
function startOfYear(date: string): string { const value = toDateValue(date); value.setUTCMonth(0, 1); return formatDateValue(value); }
function inDateRange(value: string | null, startDate: string, endDate: string): boolean { return !!value && value >= startDate && value <= endDate; }
function emptyTotals(): ReportTotals { return { shiftCount: 0, submittedQty: 0, readyQty: 0, deliveredQty: 0, replacementDeliveredQty: 0, paidQty: 0, deferredQty: 0, remadeQty: 0, cancelledQty: 0, waivedQty: 0, netSales: 0, cashSales: 0, deferredSales: 0, repaymentTotal: 0, complaintTotal: 0, complaintOpen: 0, complaintResolved: 0, complaintDismissed: 0, complaintRemake: 0, complaintCancel: 0, complaintWaive: 0, openSessions: 0, closedSessions: 0, totalSessions: 0 }; }
function createShiftRow(row: ShiftRow): ReportShiftRow { return { shiftId: row.id, kind: row.shift_kind, status: row.status, openedAt: row.opened_at, closedAt: row.closed_at, businessDate: row.business_date, ...emptyTotals(), shiftCount: 1 }; }
function addTotals(target: ReportTotals, source: ReportTotals) { target.shiftCount += source.shiftCount; target.submittedQty += source.submittedQty; target.readyQty += source.readyQty; target.deliveredQty += source.deliveredQty; target.replacementDeliveredQty += source.replacementDeliveredQty; target.paidQty += source.paidQty; target.deferredQty += source.deferredQty; target.remadeQty += source.remadeQty; target.cancelledQty += source.cancelledQty; target.waivedQty += source.waivedQty; target.netSales += source.netSales; target.cashSales += source.cashSales; target.deferredSales += source.deferredSales; target.repaymentTotal += source.repaymentTotal; target.complaintTotal += source.complaintTotal; target.complaintOpen += source.complaintOpen; target.complaintResolved += source.complaintResolved; target.complaintDismissed += source.complaintDismissed; target.complaintRemake += source.complaintRemake; target.complaintCancel += source.complaintCancel; target.complaintWaive += source.complaintWaive; target.openSessions += source.openSessions; target.closedSessions += source.closedSessions; target.totalSessions += source.totalSessions; }
function createProductRow(productId: string, productName: string, stationCode: StationCode): ProductReportRow { return { productId, productName, stationCode, qtySubmitted: 0, qtyReady: 0, qtyDelivered: 0, qtyReplacementDelivered: 0, qtyPaid: 0, qtyDeferred: 0, qtyRemade: 0, qtyCancelled: 0, qtyWaived: 0, grossSales: 0, netSales: 0 }; }
function mergeProductRows(target: ProductReportRow, source: ProductReportRow) { target.qtySubmitted += source.qtySubmitted; target.qtyReady += source.qtyReady; target.qtyDelivered += source.qtyDelivered; target.qtyReplacementDelivered += source.qtyReplacementDelivered; target.qtyPaid += source.qtyPaid; target.qtyDeferred += source.qtyDeferred; target.qtyRemade += source.qtyRemade; target.qtyCancelled += source.qtyCancelled; target.qtyWaived += source.qtyWaived; target.grossSales += source.grossSales; target.netSales += source.netSales; }
function createStaffRow(actorLabel: string): StaffPerformanceRow { return { actorLabel, submittedQty: 0, readyQty: 0, deliveredQty: 0, replacementDeliveredQty: 0, remadeQty: 0, cancelledQty: 0, waivedQty: 0, paymentTotal: 0, cashSales: 0, deferredSales: 0, repaymentTotal: 0, complaintCount: 0 }; }
function mergeStaffRows(target: StaffPerformanceRow, source: StaffPerformanceRow) { target.submittedQty += source.submittedQty; target.readyQty += source.readyQty; target.deliveredQty += source.deliveredQty; target.replacementDeliveredQty += source.replacementDeliveredQty; target.remadeQty += source.remadeQty; target.cancelledQty += source.cancelledQty; target.waivedQty += source.waivedQty; target.paymentTotal += source.paymentTotal; target.cashSales += source.cashSales; target.deferredSales += source.deferredSales; target.repaymentTotal += source.repaymentTotal; target.complaintCount += source.complaintCount; }
function sortProducts(rows: ProductReportRow[]): ProductReportRow[] { return [...rows].sort((l, r) => r.netSales - l.netSales || r.qtyDelivered - l.qtyDelivered || r.qtyReplacementDelivered - l.qtyReplacementDelivered || l.productName.localeCompare(r.productName, 'ar')); }
function sortStaff(rows: StaffPerformanceRow[]): StaffPerformanceRow[] { return [...rows].sort((l, r) => r.paymentTotal - l.paymentTotal || r.deliveredQty - l.deliveredQty || r.remadeQty - l.remadeQty || l.actorLabel.localeCompare(r.actorLabel, 'ar')); }
function sortShifts(rows: ReportShiftRow[]): ReportShiftRow[] { return [...rows].sort((l, r) => (r.businessDate ?? '').localeCompare(l.businessDate ?? '') || r.openedAt.localeCompare(l.openedAt)); }
function actorLabelFromIds(row: { by_staff_id?: string | null; by_owner_id?: string | null }, maps: ActorMaps): string | null { if (row.by_owner_id) return maps.ownerNames.get(String(row.by_owner_id)) ?? 'owner'; if (row.by_staff_id) return maps.staffNames.get(String(row.by_staff_id)) ?? 'staff'; return null; }
function createEmptyDayRow(businessDate: string): ReportBusinessDayRow { return { businessDate, ...emptyTotals() }; }
function buildPeriodReport(input: { key: ReportPeriodKey; label: string; startDate: string; endDate: string; shiftRows: ReportShiftRow[]; productsByShift: Map<string, Map<string, ProductReportRow>>; staffByShift: Map<string, Map<string, StaffPerformanceRow>>; }): PeriodReport {
  const shifts = sortShifts(input.shiftRows.filter((row) => inDateRange(row.businessDate, input.startDate, input.endDate)));
  const totals = emptyTotals(); const daysByDate = new Map<string, ReportBusinessDayRow>(); const productsById = new Map<string, ProductReportRow>(); const staffByLabel = new Map<string, StaffPerformanceRow>();
  for (const row of shifts) {
    addTotals(totals, row);
    if (row.businessDate) { const dayRow = daysByDate.get(row.businessDate) ?? createEmptyDayRow(row.businessDate); addTotals(dayRow, row); daysByDate.set(row.businessDate, dayRow); }
    for (const product of input.productsByShift.get(row.shiftId)?.values() ?? []) { const current = productsById.get(product.productId) ?? createProductRow(product.productId, product.productName, product.stationCode); mergeProductRows(current, product); productsById.set(product.productId, current); }
    for (const staff of input.staffByShift.get(row.shiftId)?.values() ?? []) { const current = staffByLabel.get(staff.actorLabel) ?? createStaffRow(staff.actorLabel); mergeStaffRows(current, staff); staffByLabel.set(staff.actorLabel, current); }
  }
  return { key: input.key, label: input.label, startDate: input.startDate, endDate: input.endDate, totals, days: Array.from(daysByDate.values()).sort((l, r) => r.businessDate.localeCompare(l.businessDate)), shifts, products: sortProducts(Array.from(productsById.values())), staff: sortStaff(Array.from(staffByLabel.values())) };
}
async function loadActorMaps(cafeId: string): Promise<ActorMaps> { const admin = adminOps(); const [{ data: staffRows, error: staffError }, { data: ownerRows, error: ownerError }] = await Promise.all([admin.from('staff_members').select('id, full_name').eq('cafe_id', cafeId), admin.from('owner_users').select('id, full_name').eq('cafe_id', cafeId)]); if (staffError) throw staffError; if (ownerError) throw ownerError; return { staffNames: new Map(((staffRows ?? []) as NamedActorRow[]).map((row) => [String(row.id), String(row.full_name ?? 'staff')])), ownerNames: new Map(((ownerRows ?? []) as NamedActorRow[]).map((row) => [String(row.id), String(row.full_name ?? 'owner')])) }; }
async function resolveReferenceDate(cafeId: string): Promise<string> { const admin = adminOps(); const [{ data: openShift, error: openError }, { data: latestShift, error: latestError }] = await Promise.all([admin.from('shifts').select('business_date').eq('cafe_id', cafeId).eq('status', 'open').order('opened_at', { ascending: false }).limit(1).maybeSingle(), admin.from('shifts').select('business_date').eq('cafe_id', cafeId).order('business_date', { ascending: false }).order('opened_at', { ascending: false }).limit(1).maybeSingle()]); if (openError) throw openError; if (latestError) throw latestError; return String((openShift as BusinessDateRow | null)?.business_date ?? (latestShift as BusinessDateRow | null)?.business_date ?? cairoToday()); }

export async function buildReportsWorkspace(cafeId: string): Promise<ReportsWorkspace> {
  const admin = adminOps(); const referenceDate = await resolveReferenceDate(cafeId); const ranges = { day: { key: 'day' as const, label: 'اليوم', startDate: referenceDate, endDate: referenceDate }, week: { key: 'week' as const, label: 'الأسبوع', startDate: startOfWeek(referenceDate), endDate: referenceDate }, month: { key: 'month' as const, label: 'الشهر', startDate: startOfMonth(referenceDate), endDate: referenceDate }, year: { key: 'year' as const, label: 'السنة', startDate: startOfYear(referenceDate), endDate: referenceDate } };
  const [actorMaps, deferredCustomers, shiftsResponse] = await Promise.all([loadActorMaps(cafeId), buildDeferredCustomersWorkspace(cafeId), admin.from('shifts').select('id, shift_kind, status, opened_at, closed_at, business_date').eq('cafe_id', cafeId).gte('business_date', ranges.year.startDate).lte('business_date', ranges.year.endDate).order('business_date', { ascending: false }).order('opened_at', { ascending: false })]);
  if (shiftsResponse.error) throw shiftsResponse.error;
  const shifts = ((shiftsResponse.data ?? []) as Record<string, unknown>[]).map((row) => ({ id: String(row.id), shift_kind: String(row.shift_kind ?? ''), status: String(row.status ?? ''), opened_at: String(row.opened_at ?? ''), closed_at: row.closed_at ? String(row.closed_at) : null, business_date: row.business_date ? String(row.business_date) : null }) satisfies ShiftRow);
  const shiftMap = new Map<string, ReportShiftRow>(); for (const shift of shifts) shiftMap.set(shift.id, createShiftRow(shift)); const shiftIds = shifts.map((row) => row.id); const productsByShift = new Map<string, Map<string, ProductReportRow>>(); const staffByShift = new Map<string, Map<string, StaffPerformanceRow>>();
  if (!shiftIds.length) return { referenceDate, currentShift: null, currentProducts: [], currentStaff: [], periods: { day: buildPeriodReport({ ...ranges.day, shiftRows: [], productsByShift, staffByShift }), week: buildPeriodReport({ ...ranges.week, shiftRows: [], productsByShift, staffByShift }), month: buildPeriodReport({ ...ranges.month, shiftRows: [], productsByShift, staffByShift }), year: buildPeriodReport({ ...ranges.year, shiftRows: [], productsByShift, staffByShift }) }, deferredCustomers: deferredCustomers as DeferredCustomerSummary[] };
  const [{ data: itemRows, error: itemError }, { data: paymentRows, error: paymentError }, { data: sessionRows, error: sessionError }, { data: complaintRows, error: complaintError }, { data: fulfillmentRows, error: fulfillmentError }] = await Promise.all([
    admin.from('order_items').select('id, shift_id, station_code, unit_price, qty_submitted, qty_ready, qty_delivered, qty_replacement_delivered, qty_paid, qty_deferred, qty_remade, qty_cancelled, qty_waived, menu_products!inner(id, product_name)').eq('cafe_id', cafeId).in('shift_id', shiftIds),
    admin.from('payments').select('id, shift_id, payment_kind, total_amount, by_staff_id, by_owner_id').eq('cafe_id', cafeId).in('shift_id', shiftIds),
    admin.from('service_sessions').select('id, shift_id, status').eq('cafe_id', cafeId).in('shift_id', shiftIds),
    admin.from('complaints').select('id, shift_id, status, resolution_kind, created_by_staff_id, created_by_owner_id').eq('cafe_id', cafeId).in('shift_id', shiftIds),
    admin.from('fulfillment_events').select('id, shift_id, event_code, quantity, by_staff_id, by_owner_id').eq('cafe_id', cafeId).in('shift_id', shiftIds),
  ]);
  if (itemError) throw itemError; if (paymentError) throw paymentError; if (sessionError) throw sessionError; if (complaintError) throw complaintError; if (fulfillmentError) throw fulfillmentError;
  for (const row of (itemRows ?? []) as ItemRow[]) { const shiftId = String(row.shift_id ?? ''); const shift = shiftMap.get(shiftId); if (!shift) continue; const qtySubmitted = Number(row.qty_submitted ?? 0); const qtyReady = Number(row.qty_ready ?? 0); const qtyDelivered = Number(row.qty_delivered ?? 0); const qtyReplacementDelivered = Number(row.qty_replacement_delivered ?? 0); const qtyPaid = Number(row.qty_paid ?? 0); const qtyDeferred = Number(row.qty_deferred ?? 0); const qtyRemade = Number(row.qty_remade ?? 0); const qtyCancelled = Number(row.qty_cancelled ?? 0); const qtyWaived = Number(row.qty_waived ?? 0); const unitPrice = Number(row.unit_price ?? 0); const grossSales = qtyDelivered * unitPrice; const netSales = Math.max(qtyDelivered - qtyWaived, 0) * unitPrice; shift.submittedQty += qtySubmitted; shift.readyQty += qtyReady; shift.deliveredQty += qtyDelivered; shift.replacementDeliveredQty += qtyReplacementDelivered; shift.paidQty += qtyPaid; shift.deferredQty += qtyDeferred; shift.remadeQty += qtyRemade; shift.cancelledQty += qtyCancelled; shift.waivedQty += qtyWaived; shift.netSales += netSales; const productRef = Array.isArray(row.menu_products) ? row.menu_products[0] : row.menu_products; const productId = String(productRef?.id ?? ''); if (!productId) continue; const stationCode = String(row.station_code ?? 'barista') as StationCode; const shiftProducts = productsByShift.get(shiftId) ?? new Map<string, ProductReportRow>(); const product = shiftProducts.get(productId) ?? createProductRow(productId, String(productRef?.product_name ?? ''), stationCode); product.qtySubmitted += qtySubmitted; product.qtyReady += qtyReady; product.qtyDelivered += qtyDelivered; product.qtyReplacementDelivered += qtyReplacementDelivered; product.qtyPaid += qtyPaid; product.qtyDeferred += qtyDeferred; product.qtyRemade += qtyRemade; product.qtyCancelled += qtyCancelled; product.qtyWaived += qtyWaived; product.grossSales += grossSales; product.netSales += netSales; shiftProducts.set(productId, product); productsByShift.set(shiftId, shiftProducts); }
  for (const row of (paymentRows ?? []) as PaymentRow[]) { const shiftId = String(row.shift_id ?? ''); const shift = shiftMap.get(shiftId); if (!shift) continue; const amount = Number(row.total_amount ?? 0); const paymentKind = String(row.payment_kind ?? ''); if (paymentKind === 'cash' || paymentKind === 'mixed') shift.cashSales += amount; if (paymentKind === 'deferred') shift.deferredSales += amount; if (paymentKind === 'repayment') shift.repaymentTotal += amount; const actorLabel = actorLabelFromIds({ by_staff_id: row.by_staff_id, by_owner_id: row.by_owner_id }, actorMaps); if (!actorLabel) continue; const shiftStaff = staffByShift.get(shiftId) ?? new Map<string, StaffPerformanceRow>(); const staff = shiftStaff.get(actorLabel) ?? createStaffRow(actorLabel); staff.paymentTotal += amount; if (paymentKind === 'cash' || paymentKind === 'mixed') staff.cashSales += amount; if (paymentKind === 'deferred') staff.deferredSales += amount; if (paymentKind === 'repayment') staff.repaymentTotal += amount; shiftStaff.set(actorLabel, staff); staffByShift.set(shiftId, shiftStaff); }
  for (const row of (sessionRows ?? []) as SessionRow[]) { const shiftId = String(row.shift_id ?? ''); const shift = shiftMap.get(shiftId); if (!shift) continue; const status = String(row.status ?? ''); if (status === 'open') shift.openSessions += 1; else if (status === 'closed') shift.closedSessions += 1; shift.totalSessions += 1; }
  for (const row of (complaintRows ?? []) as ComplaintAggRow[]) { const shiftId = String(row.shift_id ?? ''); const shift = shiftMap.get(shiftId); if (!shift) continue; shift.complaintTotal += 1; const status = String(row.status ?? ''); if (status === 'open') shift.complaintOpen += 1; if (status === 'resolved') shift.complaintResolved += 1; if (status === 'dismissed') shift.complaintDismissed += 1; const resolutionKind = String(row.resolution_kind ?? ''); if (resolutionKind === 'remake') shift.complaintRemake += 1; if (resolutionKind === 'cancel_undelivered') shift.complaintCancel += 1; if (resolutionKind === 'waive_delivered') shift.complaintWaive += 1; const actorLabel = actorLabelFromIds({ by_staff_id: row.created_by_staff_id, by_owner_id: row.created_by_owner_id }, actorMaps); if (!actorLabel) continue; const shiftStaff = staffByShift.get(shiftId) ?? new Map<string, StaffPerformanceRow>(); const staff = shiftStaff.get(actorLabel) ?? createStaffRow(actorLabel); staff.complaintCount += 1; shiftStaff.set(actorLabel, staff); staffByShift.set(shiftId, shiftStaff); }
  for (const row of (fulfillmentRows ?? []) as FulfillmentAggRow[]) { const shiftId = String(row.shift_id ?? ''); if (!shiftMap.has(shiftId)) continue; const actorLabel = actorLabelFromIds({ by_staff_id: row.by_staff_id, by_owner_id: row.by_owner_id }, actorMaps); if (!actorLabel) continue; const quantity = Number(row.quantity ?? 0); const eventCode = String(row.event_code ?? ''); const shiftStaff = staffByShift.get(shiftId) ?? new Map<string, StaffPerformanceRow>(); const staff = shiftStaff.get(actorLabel) ?? createStaffRow(actorLabel); if (eventCode === 'submitted') staff.submittedQty += quantity; if (eventCode === 'remake_submitted') staff.remadeQty += quantity; if (eventCode === 'partial_ready' || eventCode === 'ready') staff.readyQty += quantity; if (eventCode === 'delivered') staff.deliveredQty += quantity; if (eventCode === 'remake_delivered') staff.replacementDeliveredQty += quantity; if (eventCode === 'cancelled') staff.cancelledQty += quantity; if (eventCode === 'waived') staff.waivedQty += quantity; shiftStaff.set(actorLabel, staff); staffByShift.set(shiftId, shiftStaff); }
  const shiftRows = Array.from(shiftMap.values()); const currentShift = sortShifts(shiftRows.filter((row) => row.status === 'open'))[0] ?? null; const currentProducts = currentShift ? sortProducts(Array.from(productsByShift.get(currentShift.shiftId)?.values() ?? [])) : []; const currentStaff = currentShift ? sortStaff(Array.from(staffByShift.get(currentShift.shiftId)?.values() ?? [])) : [];
  return { referenceDate, currentShift, currentProducts, currentStaff, periods: { day: buildPeriodReport({ ...ranges.day, shiftRows, productsByShift, staffByShift }), week: buildPeriodReport({ ...ranges.week, shiftRows, productsByShift, staffByShift }), month: buildPeriodReport({ ...ranges.month, shiftRows, productsByShift, staffByShift }), year: buildPeriodReport({ ...ranges.year, shiftRows, productsByShift, staffByShift }) }, deferredCustomers: deferredCustomers as DeferredCustomerSummary[] };
}
